export const slideDataImages = [
  { id: 1, src: "/image.png", alt: "" },
  { id: 2, src: "https://swiperjs.com/demos/images/nature-2.jpg", alt: "" },
  { id: 3, src: "/image.png", alt: "" },
  { id: 4, src: "https://swiperjs.com/demos/images/nature-4.jpg", alt: "" },
  { id: 5, src: "/image.png", alt: "" },
  { id: 6, src: "https://swiperjs.com/demos/images/nature-6.jpg", alt: "" },
  { id: 7, src: "/image.png", alt: "" },
  { id: 8, src: "https://swiperjs.com/demos/images/nature-8.jpg", alt: "" },
  { id: 9, src: "/image.png", alt: "" },
  { id: 10, src: "https://swiperjs.com/demos/images/nature-10.jpg", alt: "" },
  { id: 11, src: "/makima.png", alt: "" },
  { id: 12, src: "/makima.png", alt: "" },
  { id: 13, src: "/makima.png", alt: "" },
  { id: 14, src: "/makima.png", alt: "" },
  { id: 15, src: "/makima.png", alt: "" },
  { id: 16, src: "/makima.png", alt: "" },
];
// export const slideDataImages = [
//   { id: 1, src: "https://swiperjs.com/demos/images/nature-1.jpg", alt: "" },
//   { id: 2, src: "https://swiperjs.com/demos/images/nature-2.jpg", alt: "" },
//   { id: 3, src: "https://swiperjs.com/demos/images/nature-3.jpg", alt: "" },
//   { id: 4, src: "https://swiperjs.com/demos/images/nature-4.jpg", alt: "" },
//   { id: 5, src: "https://swiperjs.com/demos/images/nature-5.jpg", alt: "" },
//   { id: 6, src: "https://swiperjs.com/demos/images/nature-6.jpg", alt: "" },
//   { id: 7, src: "https://swiperjs.com/demos/images/nature-7.jpg", alt: "" },
//   { id: 8, src: "https://swiperjs.com/demos/images/nature-8.jpg", alt: "" },
//   { id: 9, src: "https://swiperjs.com/demos/images/nature-9.jpg", alt: "" },
//   { id: 10, src: "https://swiperjs.com/demos/images/nature-10.jpg", alt: "" },
//   { id: 11, src: "https://swiperjs.com/demos/images/nature-1.jpg", alt: "" },
//   { id: 12, src: "https://swiperjs.com/demos/images/nature-2.jpg", alt: "" },
//   { id: 13, src: "https://swiperjs.com/demos/images/nature-3.jpg", alt: "" },
//   { id: 14, src: "https://swiperjs.com/demos/images/nature-4.jpg", alt: "" },
//   { id: 15, src: "https://swiperjs.com/demos/images/nature-5.jpg", alt: "" },
//   { id: 16, src: "https://swiperjs.com/demos/images/nature-6.jpg", alt: "" },
// ];
